# Generated by Django 5.0.7 on 2024-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteurl',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
